const selectors = require('../supporting/selectors')
const data = require('../supporting/data')

module.exports = {
    beforeEach: browser => {
        browser.url('http://localhost:3000')

    },
    after: browser => {
        browser.end()
    },

    "GoodTest1": browser => {
        browser
            .waitForElementVisible(selectors.homePage.nextButton, 5000)
            .click(selectors.homePage.nextButton)
            .waitForElementVisible(selectors.propertyLoanType.loanTypes, 5000)
            .click(`${selectors.propertyLoanType.loanTypes} ${selectors.propertyLoanType.refinance}`)
            .click(`${selectors.propertyLoanType.propertyTypes} ${selectors.propertyLoanType.condo}`)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.cityStateOrZip.propertyLocationPrompt, 5000)
            .click(selectors.cityStateOrZip.city)
            .setValue(selectors.cityStateOrZip.city, data.goodData.goodTest1.city)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.loanProperty.rentalProperty, 5000)
            .click(selectors.loanProperty.rentalProperty)
            .waitForElementVisible(selectors.found.yesButton, 5000)
            .expect.element(selectors.found.foundPrompt).text.to.contain("Have you already found your new home?")
        browser.click(selectors.found.noButton)
            .waitForElementVisible(selectors.found.noButton, 5000)
        browser.expect.element(selectors.propertyLoanType.promptText1).text.to.equal("Are you currently working with a real estate agent?")
        browser.click(selectors.found.noButton)
            .waitForElementVisible(selectors.priceDown.price, 5000)
            .click(selectors.priceDown.price)
            .setValue(selectors.priceDown.price, data.goodData.goodTest1.price)
            .setValue(selectors.priceDown.down, data.goodData.goodTest1.down)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.creditScore.excellent, 5000)
            .click(selectors.creditScore.excellent)
            .waitForElementVisible(selectors.bankruptcyForeclosure.bankruptcy, 5000)
            .click(selectors.bankruptcyForeclosure.neither)
            .waitForElementVisible(selectors.mailingAddress.addressTwo, 5000)
            .click(selectors.mailingAddress.addressOne)
            .setValue(selectors.mailingAddress.addressOne, data.goodData.goodTest1.addressOne)
            .setValue(selectors.mailingAddress.addressTwo, data.goodData.goodTest1.addressTwo)
            .setValue(selectors.mailingAddress.addressThree, data.goodData.goodTest1.addressThree)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.nameEmail.email, 5000)
            .setValue(selectors.nameEmail.first, data.goodData.goodTest1.first)
            .setValue(selectors.nameEmail.last, data.goodData.goodTest1.last)
            .setValue(selectors.nameEmail.email, data.goodData.goodTest1.email)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.assembledQuery.sendButton, 5000)
        browser.expect.element(selectors.assembledQuery.nameLabel).text.to.contain(data.goodData.goodTest1.fullName)
        browser.expect.element(selectors.assembledQuery.emailLabel).text.to.contain(data.goodData.goodTest1.email)
        browser.expect.element(selectors.assembledQuery.loanTypeLabel).text.to.contain(data.goodData.goodTest1.loanType)
        browser.expect.element(selectors.assembledQuery.propertyTypeLabel).text.to.contain(data.goodData.goodTest1.propertyType)
        browser.expect.element(selectors.assembledQuery.cityLabel).text.to.contain(data.goodData.goodTest1.city)
        browser.pause(5000)
        browser.expect.element(selectors.assembledQuery.propertyType).text.to.contain(data.goodData.goodTest1.propertyType)
        browser.expect.element(selectors.assembledQuery.found).text.to.equal("No")
        browser.expect.element(selectors.assembledQuery.agent).text.to.equal("No")
        browser.expect.element(selectors.assembledQuery.price).text.to.contain(data.goodData.goodTest1.price)
        browser.expect.element(selectors.assembledQuery.downPayment).text.to.contain(data.goodData.goodTest1.down)
        browser.expect.element(selectors.assembledQuery.creditScore).text.to.contain("Excellent")
        browser.expect.element(selectors.assembledQuery.creditHistory).text.to.contain("Has not been in bankruptcy or foreclosure")
        browser.expect.element(selectors.assembledQuery.addressLine1).text.to.contain(data.goodData.goodTest1.addressOne)
        browser.expect.element(selectors.assembledQuery.addressLine2).text.to.contain(data.goodData.goodTest1.addressTwo)
        browser.expect.element(selectors.assembledQuery.addressLine3).text.to.contain(data.goodData.goodTest1.addressThree)
        browser
            .click(selectors.assembledQuery.sendButton)
            .waitForElementVisible(selectors.thankyouPage.marginBtn, 5000)
            .click(selectors.thankyouPage.marginBtn)
            .waitForElementVisible(selectors.homePage.versionNumber, 5000)
    },
    "GoodTest2": browser => {
        browser
            .waitForElementVisible(selectors.homePage.nextButton, 5000)
            .click(selectors.homePage.nextButton)
            .waitForElementVisible(selectors.propertyLoanType.loanTypes, 5000)
            .click(`${selectors.propertyLoanType.loanTypes} ${selectors.propertyLoanType.homePurchase}`)
            .click(`${selectors.propertyLoanType.propertyTypes} ${selectors.propertyLoanType.singleFamilyHome}`)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.cityStateOrZip.propertyLocationPrompt, 5000)
            .click(selectors.cityStateOrZip.city)
            .setValue(selectors.cityStateOrZip.city, data.goodData.goodTest2.city)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.loanProperty.primaryHome, 5000)
            .click(selectors.loanProperty.primaryHome)
            .waitForElementVisible(selectors.found.yesButton, 5000)
            .expect.element(selectors.found.foundPrompt).text.to.contain("Have you already found your new home?")
        browser.click(selectors.found.yesButton)
            .waitForElementVisible(selectors.found.noButton, 5000)
        browser.expect.element(selectors.propertyLoanType.promptText1).text.to.equal("Are you currently working with a real estate agent?")
        browser.click(selectors.found.yesButton)
            .waitForElementVisible(selectors.priceDown.price, 5000)
            .click(selectors.priceDown.price)
            .setValue(selectors.priceDown.price, data.goodData.goodTest2.price)
            .setValue(selectors.priceDown.down, data.goodData.goodTest2.down)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.creditScore.excellent, 5000)
            .click(selectors.creditScore.excellent)
            .waitForElementVisible(selectors.bankruptcyForeclosure.bankruptcy, 5000)
            .click(selectors.bankruptcyForeclosure.neither)
            .waitForElementVisible(selectors.mailingAddress.addressTwo, 5000)
            .click(selectors.mailingAddress.addressOne)
            .setValue(selectors.mailingAddress.addressOne, data.goodData.goodTest2.addressOne)
            .setValue(selectors.mailingAddress.addressTwo, data.goodData.goodTest2.addressTwo)
            .setValue(selectors.mailingAddress.addressThree, data.goodData.goodTest2.addressThree)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.nameEmail.email, 5000)
            .setValue(selectors.nameEmail.first, data.goodData.goodTest2.first)
            .setValue(selectors.nameEmail.last, data.goodData.goodTest2.last)
            .setValue(selectors.nameEmail.email, data.goodData.goodTest2.email)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.assembledQuery.sendButton, 5000)
        browser.expect.element(selectors.assembledQuery.nameLabel).text.to.contain(data.goodData.goodTest2.fullName)
        browser.expect.element(selectors.assembledQuery.emailLabel).text.to.contain(data.goodData.goodTest2.email)
        browser.expect.element(selectors.assembledQuery.loanTypeLabel).text.to.contain(data.goodData.goodTest2.loanType)
        browser.expect.element(selectors.assembledQuery.propertyTypeLabel).text.to.contain(data.goodData.goodTest2.propertyType)
        browser.expect.element(selectors.assembledQuery.cityLabel).text.to.contain(data.goodData.goodTest2.city)
        browser.expect.element(selectors.assembledQuery.propertyType).text.to.contain(data.goodData.goodTest2.propertyType)
        browser.expect.element(selectors.assembledQuery.found).text.to.equal("Yes")
        browser.expect.element(selectors.assembledQuery.agent).text.to.equal("Yes")
        browser.expect.element(selectors.assembledQuery.price).text.to.contain(data.goodData.goodTest2.price)
        browser.expect.element(selectors.assembledQuery.downPayment).text.to.contain(data.goodData.goodTest2.down)
        browser.expect.element(selectors.assembledQuery.creditScore).text.to.contain("Excellent")
        browser.expect.element(selectors.assembledQuery.creditHistory).text.to.contain("Has not been in bankruptcy or foreclosure")
        browser.expect.element(selectors.assembledQuery.addressLine1).text.to.contain(data.goodData.goodTest2.addressOne)
        browser.expect.element(selectors.assembledQuery.addressLine2).text.to.contain(data.goodData.goodTest2.addressTwo)
        browser.expect.element(selectors.assembledQuery.addressLine3).text.to.contain(data.goodData.goodTest2.addressThree)
        browser
            .click(selectors.assembledQuery.sendButton)
            .waitForElementVisible(selectors.thankyouPage.marginBtn, 5000)
            .click(selectors.thankyouPage.marginBtn)
            .waitForElementVisible(selectors.homePage.versionNumber, 5000)
    },

    "GoodTest3": browser => {
        browser
            .waitForElementVisible(selectors.homePage.nextButton, 5000)
            .click(selectors.homePage.nextButton)
            .waitForElementVisible(selectors.propertyLoanType.loanTypes, 5000)
            .click(`${selectors.propertyLoanType.loanTypes} ${selectors.propertyLoanType.homeEquity}`)
            .click(`${selectors.propertyLoanType.propertyTypes} ${selectors.propertyLoanType.townHome}`)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.cityStateOrZip.propertyLocationPrompt, 5000)
            .click(selectors.cityStateOrZip.city)
            .setValue(selectors.cityStateOrZip.city, data.goodData.goodTest3.city)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.loanProperty.secondaryHome, 5000)
            .click(selectors.loanProperty.secondaryHome)
            .waitForElementVisible(selectors.found.yesButton, 5000)
            .expect.element(selectors.found.foundPrompt).text.to.contain("Have you already found your new home?")
        browser.click(selectors.found.yesButton)
            .waitForElementVisible(selectors.found.noButton, 5000)
        browser.expect.element(selectors.propertyLoanType.promptText1).text.to.equal("Are you currently working with a real estate agent?")
        browser.click(selectors.found.noButton)
            .waitForElementVisible(selectors.priceDown.price, 5000)
            .click(selectors.priceDown.price)
            .setValue(selectors.priceDown.price, data.goodData.goodTest3.price)
            .setValue(selectors.priceDown.down, data.goodData.goodTest3.down)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.creditScore.good, 5000)
            .click(selectors.creditScore.good)
            .waitForElementVisible(selectors.bankruptcyForeclosure.bankruptcy, 5000)
            .click(selectors.bankruptcyForeclosure.bankruptcy)
            .waitForElementVisible(selectors.mailingAddress.addressTwo, 5000)
            .click(selectors.mailingAddress.addressOne)
            .setValue(selectors.mailingAddress.addressOne, data.goodData.goodTest3.addressOne)
            .setValue(selectors.mailingAddress.addressThree, data.goodData.goodTest3.addressThree)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.nameEmail.email, 5000)
            .setValue(selectors.nameEmail.first, data.goodData.goodTest3.first)
            .setValue(selectors.nameEmail.last, data.goodData.goodTest3.last)
            .setValue(selectors.nameEmail.email, data.goodData.goodTest3.email)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.assembledQuery.sendButton, 5000)
        browser.expect.element(selectors.assembledQuery.nameLabel).text.to.contain(data.goodData.goodTest3.fullName)
        browser.expect.element(selectors.assembledQuery.emailLabel).text.to.contain(data.goodData.goodTest3.email)
        browser.expect.element(selectors.assembledQuery.loanTypeLabel).text.to.contain(data.goodData.goodTest3.loanType)
        browser.expect.element(selectors.assembledQuery.propertyTypeLabel).text.to.contain(data.goodData.goodTest3.propertyType)
        browser.expect.element(selectors.assembledQuery.cityLabel).text.to.contain(data.goodData.goodTest3.city)
        browser.expect.element(selectors.assembledQuery.propertyType).text.to.contain(data.goodData.goodTest3.propertyType)
        browser.expect.element(selectors.assembledQuery.found).text.to.equal("Yes")
        browser.expect.element(selectors.assembledQuery.agent).text.to.equal("No")
        browser.expect.element(selectors.assembledQuery.price).text.to.contain(data.goodData.goodTest3.price)
        browser.expect.element(selectors.assembledQuery.downPayment).text.to.contain(data.goodData.goodTest3.down)
        browser.expect.element(selectors.assembledQuery.creditScore).text.to.contain("Good")
        browser.expect.element(selectors.assembledQuery.creditHistory).text.to.contain("Has had bankruptcy")
        browser.expect.element(selectors.assembledQuery.addressLine1).text.to.contain(data.goodData.goodTest3.addressOne)
        browser.expect.element(selectors.assembledQuery.addressLine3).text.to.contain(data.goodData.goodTest3.addressThree)
        browser
            .click(selectors.assembledQuery.sendButton)
            .waitForElementVisible(selectors.thankyouPage.marginBtn, 5000)
            .click(selectors.thankyouPage.marginBtn)
            .waitForElementVisible(selectors.homePage.versionNumber, 5000)
    },
    "GoodTest4": browser => {
        browser
            .waitForElementVisible(selectors.homePage.nextButton, 5000)
            .click(selectors.homePage.nextButton)
            .waitForElementVisible(selectors.propertyLoanType.loanTypes, 5000)
            .click(`${selectors.propertyLoanType.loanTypes} ${selectors.propertyLoanType.homePurchase}`)
            .click(`${selectors.propertyLoanType.propertyTypes} ${selectors.propertyLoanType.multiFamilyDwelling}`)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.cityStateOrZip.propertyLocationPrompt, 5000)
            .click(selectors.cityStateOrZip.city)
            .setValue(selectors.cityStateOrZip.city, data.goodData.goodTest4.city)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.loanProperty.secondaryHome, 5000)
            .click(selectors.loanProperty.secondaryHome)
            .waitForElementVisible(selectors.found.yesButton, 5000)
            .expect.element(selectors.found.foundPrompt).text.to.contain("Have you already found your new home?")
        browser.click(selectors.found.noButton)
            .waitForElementVisible(selectors.found.noButton, 5000)
        browser.expect.element(selectors.propertyLoanType.promptText1).text.to.equal("Are you currently working with a real estate agent?")
        browser.click(selectors.found.yesButton)
            .waitForElementVisible(selectors.priceDown.price, 5000)
            .click(selectors.priceDown.price)
            .setValue(selectors.priceDown.price, data.goodData.goodTest4.price)
            .setValue(selectors.priceDown.down, data.goodData.goodTest4.down)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.creditScore.fair, 5000)
            .click(selectors.creditScore.fair)
            .waitForElementVisible(selectors.bankruptcyForeclosure.bankruptcy, 5000)
            .click(selectors.bankruptcyForeclosure.foreclosure)
            .waitForElementVisible(selectors.mailingAddress.addressTwo, 5000)
            .click(selectors.mailingAddress.addressOne)
            .setValue(selectors.mailingAddress.addressOne, data.goodData.goodTest4.addressOne)
            .setValue(selectors.mailingAddress.addressTwo, data.goodData.goodTest4.addressTwo)
            .setValue(selectors.mailingAddress.addressThree, data.goodData.goodTest4.addressThree)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.nameEmail.email, 5000)
            .setValue(selectors.nameEmail.first, data.goodData.goodTest4.first)
            .setValue(selectors.nameEmail.last, data.goodData.goodTest4.last)
            .setValue(selectors.nameEmail.email, data.goodData.goodTest4.email)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.assembledQuery.sendButton, 5000)
        browser.expect.element(selectors.assembledQuery.nameLabel).text.to.contain(data.goodData.goodTest4.fullName)
        browser.expect.element(selectors.assembledQuery.emailLabel).text.to.contain(data.goodData.goodTest4.email)
        browser.expect.element(selectors.assembledQuery.loanTypeLabel).text.to.contain(data.goodData.goodTest4.loanType)
        browser.expect.element(selectors.assembledQuery.propertyTypeLabel).text.to.contain(data.goodData.goodTest4.propertyType)
        browser.expect.element(selectors.assembledQuery.cityLabel).text.to.contain(data.goodData.goodTest4.city)
        browser.pause(5000)
        browser.expect.element(selectors.assembledQuery.propertyType).text.to.contain(data.goodData.goodTest4.propertyType)
        browser.expect.element(selectors.assembledQuery.found).text.to.equal("No")
        browser.expect.element(selectors.assembledQuery.agent).text.to.equal("Yes")
        browser.expect.element(selectors.assembledQuery.price).text.to.contain(data.goodData.goodTest4.price)
        browser.expect.element(selectors.assembledQuery.downPayment).text.to.contain(data.goodData.goodTest4.down)
        browser.expect.element(selectors.assembledQuery.creditScore).text.to.contain("Fair")
        browser.expect.element(selectors.assembledQuery.creditHistory).text.to.contain("Has had a foreclosure")
        browser.expect.element(selectors.assembledQuery.addressLine1).text.to.contain(data.goodData.goodTest4.addressOne)
        browser.expect.element(selectors.assembledQuery.addressLine2).text.to.contain(data.goodData.goodTest4.addressTwo)
        browser.expect.element(selectors.assembledQuery.addressLine3).text.to.contain(data.goodData.goodTest4.addressThree)
        browser
            .click(selectors.assembledQuery.sendButton)
            .waitForElementVisible(selectors.thankyouPage.marginBtn, 5000)
            .click(selectors.thankyouPage.marginBtn)
            .waitForElementVisible(selectors.homePage.versionNumber, 5000)
    },
    "GoodTest5": browser => {
        browser
            .waitForElementVisible(selectors.homePage.nextButton, 5000)
            .click(selectors.homePage.nextButton)
            .waitForElementVisible(selectors.propertyLoanType.loanTypes, 5000)
            .click(`${selectors.propertyLoanType.loanTypes} ${selectors.propertyLoanType.homeEquity}`)
            .click(`${selectors.propertyLoanType.propertyTypes} ${selectors.propertyLoanType.mobileHome}`)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.cityStateOrZip.propertyLocationPrompt, 5000)
            .click(selectors.cityStateOrZip.city)
            .setValue(selectors.cityStateOrZip.city, data.goodData.goodTest5.city)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.loanProperty.secondaryHome, 5000)
            .click(selectors.loanProperty.secondaryHome)
            .waitForElementVisible(selectors.found.yesButton, 5000)
            .expect.element(selectors.found.foundPrompt).text.to.contain("Have you already found your new home?")
        browser.click(selectors.found.yesButton)
            .waitForElementVisible(selectors.found.noButton, 5000)
        browser.expect.element(selectors.propertyLoanType.promptText1).text.to.equal("Are you currently working with a real estate agent?")
        browser.click(selectors.found.noButton)
            .waitForElementVisible(selectors.priceDown.price, 5000)
            .click(selectors.priceDown.price)
            .setValue(selectors.priceDown.price, data.goodData.goodTest5.price)
            .setValue(selectors.priceDown.down, data.goodData.goodTest5.down)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.creditScore.poor, 5000)
            .click(selectors.creditScore.poor)
            .waitForElementVisible(selectors.bankruptcyForeclosure.bankruptcy, 5000)
            .click(selectors.bankruptcyForeclosure.both)
            .waitForElementVisible(selectors.mailingAddress.addressTwo, 5000)
            .click(selectors.mailingAddress.addressOne)
            .setValue(selectors.mailingAddress.addressOne, data.goodData.goodTest5.addressOne)
            .setValue(selectors.mailingAddress.addressThree, data.goodData.goodTest5.addressThree)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.nameEmail.email, 5000)
            .setValue(selectors.nameEmail.first, data.goodData.goodTest5.first)
            .setValue(selectors.nameEmail.last, data.goodData.goodTest5.last)
            .setValue(selectors.nameEmail.email, data.goodData.goodTest5.email)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.assembledQuery.sendButton, 5000)
        browser.expect.element(selectors.assembledQuery.nameLabel).text.to.contain(data.goodData.goodTest5.fullName)
        browser.expect.element(selectors.assembledQuery.emailLabel).text.to.contain(data.goodData.goodTest5.email)
        browser.expect.element(selectors.assembledQuery.loanTypeLabel).text.to.contain(data.goodData.goodTest5.loanType)
        browser.expect.element(selectors.assembledQuery.propertyTypeLabel).text.to.contain(data.goodData.goodTest5.propertyType)
        browser.expect.element(selectors.assembledQuery.cityLabel).text.to.contain(data.goodData.goodTest5.city)
        browser.pause(5000)
        browser.expect.element(selectors.assembledQuery.propertyType).text.to.contain(data.goodData.goodTest5.propertyType)
        browser.expect.element(selectors.assembledQuery.found).text.to.equal("Yes")
        browser.expect.element(selectors.assembledQuery.agent).text.to.equal("No")
        browser.expect.element(selectors.assembledQuery.price).text.to.contain(data.goodData.goodTest5.price)
        browser.expect.element(selectors.assembledQuery.downPayment).text.to.contain(data.goodData.goodTest5.down)
        browser.expect.element(selectors.assembledQuery.creditScore).text.to.contain("Poor")
        browser.expect.element(selectors.assembledQuery.creditHistory).text.to.contain("Has had both a foreclosure and a bankruptcy")
        browser.expect.element(selectors.assembledQuery.addressLine1).text.to.contain(data.goodData.goodTest5.addressOne)
        browser.expect.element(selectors.assembledQuery.addressLine3).text.to.contain(data.goodData.goodTest5.addressThree)
        browser
            .click(selectors.assembledQuery.sendButton)
            .waitForElementVisible(selectors.thankyouPage.marginBtn, 5000)
            .click(selectors.thankyouPage.marginBtn)
            .waitForElementVisible(selectors.homePage.versionNumber, 5000)
    },
    "GoodTest6": browser => {
        browser
            .waitForElementVisible(selectors.homePage.nextButton, 5000)
            .click(selectors.homePage.nextButton)
            .waitForElementVisible(selectors.propertyLoanType.loanTypes, 5000)
            .click(`${selectors.propertyLoanType.loanTypes} ${selectors.propertyLoanType.homePurchase}`)
            .click(`${selectors.propertyLoanType.propertyTypes} ${selectors.propertyLoanType.singleFamilyHome}`)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.cityStateOrZip.propertyLocationPrompt, 5000)
            .click(selectors.cityStateOrZip.city)
            .setValue(selectors.cityStateOrZip.city, data.goodData.goodTest6.city)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.loanProperty.secondaryHome, 5000)
            .click(selectors.loanProperty.primaryHome)
            .waitForElementVisible(selectors.found.yesButton, 5000)
            .expect.element(selectors.found.foundPrompt).text.to.contain("Have you already found your new home?")
        browser.click(selectors.found.yesButton)
            .waitForElementVisible(selectors.found.noButton, 5000)
        browser.expect.element(selectors.propertyLoanType.promptText1).text.to.equal("Are you currently working with a real estate agent?")
        browser.click(selectors.found.yesButton)
            .waitForElementVisible(selectors.priceDown.price, 5000)
            .click(selectors.priceDown.price)
            .setValue(selectors.priceDown.price, data.goodData.goodTest6.price)
            .setValue(selectors.priceDown.down, data.goodData.goodTest6.down)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.creditScore.poor, 5000)
            .click(selectors.creditScore.good)
            .waitForElementVisible(selectors.bankruptcyForeclosure.bankruptcy, 5000)
            .click(selectors.bankruptcyForeclosure.bankruptcy)
            .waitForElementVisible(selectors.mailingAddress.addressTwo, 5000)
            .click(selectors.mailingAddress.addressOne)
            .setValue(selectors.mailingAddress.addressOne, data.goodData.goodTest6.addressOne)
            .setValue(selectors.mailingAddress.addressThree, data.goodData.goodTest5.addressThree)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.nameEmail.email, 5000)
            .setValue(selectors.nameEmail.first, data.goodData.goodTest6.first)
            .setValue(selectors.nameEmail.last, data.goodData.goodTest6.last)
            .setValue(selectors.nameEmail.email, data.goodData.goodTest6.email)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.assembledQuery.sendButton, 5000)
        browser.expect.element(selectors.assembledQuery.nameLabel).text.to.contain(data.goodData.goodTest6.fullName)
        browser.expect.element(selectors.assembledQuery.emailLabel).text.to.contain(data.goodData.goodTest6.email)
        browser.expect.element(selectors.assembledQuery.loanTypeLabel).text.to.contain(data.goodData.goodTest6.loanType)
        browser.expect.element(selectors.assembledQuery.propertyTypeLabel).text.to.contain(data.goodData.goodTest6.propertyType)
        browser.expect.element(selectors.assembledQuery.cityLabel).text.to.contain(data.goodData.goodTest6.city)
        browser.pause(5000)
        browser.expect.element(selectors.assembledQuery.propertyType).text.to.contain(data.goodData.goodTest6.propertyType)
        browser.expect.element(selectors.assembledQuery.found).text.to.equal("Yes")
        browser.expect.element(selectors.assembledQuery.agent).text.to.equal("Yes")
        browser.expect.element(selectors.assembledQuery.price).text.to.contain(data.goodData.goodTest6.price)
        browser.expect.element(selectors.assembledQuery.downPayment).text.to.contain(data.goodData.goodTest6.down)
        browser.expect.element(selectors.assembledQuery.creditScore).text.to.contain("Good")
        browser.expect.element(selectors.assembledQuery.creditHistory).text.to.contain("Has had bankruptcy")
        browser.expect.element(selectors.assembledQuery.addressLine1).text.to.contain(data.goodData.goodTest6.addressOne)
        browser.expect.element(selectors.assembledQuery.addressLine3).text.to.contain(data.goodData.goodTest6.addressThree)
        browser
            .click(selectors.assembledQuery.sendButton)
            .waitForElementVisible(selectors.thankyouPage.marginBtn, 5000)
            .click(selectors.thankyouPage.marginBtn)
            .waitForElementVisible(selectors.homePage.versionNumber, 5000)
    },
    "BadTest1": browser => {
        browser
            .waitForElementVisible(selectors.homePage.nextButton, 5000)
            .click(selectors.homePage.nextButton)
            .waitForElementVisible(selectors.propertyLoanType.loanTypes, 5000)
            .click(`${selectors.propertyLoanType.loanTypes} ${selectors.propertyLoanType.homeEquity}`)
            .click(`${selectors.propertyLoanType.propertyTypes} ${selectors.propertyLoanType.townHome}`)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.cityStateOrZip.propertyLocationPrompt, 5000)
            .click(selectors.cityStateOrZip.city)
            .setValue(selectors.cityStateOrZip.city, data.badTest1.city)
            .click(selectors.propertyLoanType.nextButton)
        browser.expect.element(selectors.cityStateOrZip.errorMessage).text.to.contain('This field requires a City Name (letters, periods and dashes allowed) and a State abbreviation (separated by a comma, no longer than 30 characters) or a 5 digit zip code. i.e. "94111" and "San Francisco, CA')
        browser.clearValue(selectors.cityStateOrZip.city)
            .setValue(selectors.cityStateOrZip.city, data.badTest1.goodCity)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.loanProperty.secondaryHome, 5000)
            .click(selectors.loanProperty.secondaryHome)
            .waitForElementVisible(selectors.found.yesButton, 5000)
            .expect.element(selectors.found.foundPrompt).text.to.contain("Have you already found your new home?")
        browser.click(selectors.found.noButton)
            .waitForElementVisible(selectors.found.noButton, 5000)
        browser.expect.element(selectors.propertyLoanType.promptText1).text.to.equal("Are you currently working with a real estate agent?")
        browser.click(selectors.found.noButton)
            .waitForElementVisible(selectors.priceDown.price, 5000)
            .click(selectors.priceDown.price)
            .setValue(selectors.priceDown.price, data.badTest1.price)
            .setValue(selectors.priceDown.down, data.badTest1.down)
            .click(selectors.propertyLoanType.nextButton)
        // .expect.element(selectors.propertyLoanType.errorMessage)
        // .clearValue(selectors.priceDown.down)
        // .clearValue(selectors.priceDown.price)
        // .setValue(selectors.priceDown.price, data.badTest1.goodPrice)
        // .setValue(selectors.priceDown.down, data.badTest1.goodDown)
        // .click(selectors.propertyLoanType.nextButton)
        browser.waitForElementVisible(selectors.creditScore.poor, 5000)
            .click(selectors.creditScore.excellent)
            .waitForElementVisible(selectors.bankruptcyForeclosure.bankruptcy, 5000)
            .click(selectors.bankruptcyForeclosure.neither)
            .waitForElementVisible(selectors.mailingAddress.addressTwo, 5000)
            // .click(selectors.mailingAddress.addressOne)
            .setValue(selectors.mailingAddress.addressOne, data.badTest1.addressOne)
            .setValue(selectors.mailingAddress.addressThree, data.badTest1.addressThree)
            .click(selectors.propertyLoanType.nextButton)
        browser.expect.element(selectors.mailingAddress.addThreeErrorMessage).text.to.contain('The last line must follow a standard city, state zip format (San Francisco, CA 94111), with a valid state abbreviation. It also can be no longer than 50 characters total.')
        browser.clearValue(selectors.mailingAddress.addressThree)
            .setValue(selectors.mailingAddress.addressThree, data.badTest1.goodAddressThree)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.nameEmail.email, 5000)
            .setValue(selectors.nameEmail.first, data.badTest1.first)
            .setValue(selectors.nameEmail.last, data.badTest1.last)
            .setValue(selectors.nameEmail.email, data.badTest1.email)
            .click(selectors.propertyLoanType.nextButton)
            .waitForElementVisible(selectors.assembledQuery.sendButton, 5000)
        browser.expect.element(selectors.assembledQuery.nameLabel).text.to.contain(data.badTest1.fullName)
        browser.expect.element(selectors.assembledQuery.emailLabel).text.to.contain(data.badTest1.email)
        browser.expect.element(selectors.assembledQuery.loanTypeLabel).text.to.contain(data.badTest1.loanType)
        browser.expect.element(selectors.assembledQuery.propertyTypeLabel).text.to.contain(data.badTest1.propertyType)
        browser.expect.element(selectors.assembledQuery.cityLabel).text.to.contain(data.badTest1.goodCity)
        browser.expect.element(selectors.assembledQuery.propertyType).text.to.contain(data.badTest1.propertyType)
        browser.expect.element(selectors.assembledQuery.found).text.to.equal("No")
        browser.expect.element(selectors.assembledQuery.agent).text.to.equal("No")
        browser.expect.element(selectors.assembledQuery.price).text.to.contain(data.badTest1.price)
        browser.expect.element(selectors.assembledQuery.downPayment).text.to.contain(data.badTest1.down)
        browser.expect.element(selectors.assembledQuery.creditScore).text.to.contain("Excellent")
        browser.expect.element(selectors.assembledQuery.creditHistory).text.to.contain("Has not been in bankruptcy or foreclosure")
        browser.expect.element(selectors.assembledQuery.addressLine1).text.to.contain(data.badTest1.addressOne)
        browser.expect.element(selectors.assembledQuery.addressLine3).text.to.contain(data.badTest1.goodAddressThree)
        browser
            .click(selectors.assembledQuery.sendButton)
            .waitForElementVisible(selectors.thankyouPage.marginBtn, 5000)
            .click(selectors.thankyouPage.marginBtn)
            .waitForElementVisible(selectors.homePage.versionNumber, 5000)
    },
    
}
