module.exports = {

    homePage: {

        promptText: 'h1[name="promptText"]',
        nextButton: 'button[name="nextButton"]',
        versionNumber: 'h6[name="versionNumber"]',
    },

    propertyLoanType: {
        promptText1: 'p[name="promptText"]',
        loanTypes: 'select[id="loanTypes"]',
        homePurchase: 'option[value="Home Purchase"]',
        refinance: 'option[value="Refinance"]',
        homeEquity: 'option[value="Home Equity"]',
        propertyTypes: 'select[id="propertyTypes"]',
        singleFamilyHome: 'option[value="Single Family Home"]',
        townHome: 'option[value="Town Home"]',
        condo: 'option[value="Condo"]',
        multiFamilyDwelling: 'option[value="Multi Family Dwelling"]',
        mobileHome: 'option[value="Mobile Home"]',
        nextButton: 'button[name="nextButton"]',
        errorMessage: 'li[class="errorMessage"]',
    },
    cityStateOrZip: {
        propertyLocationPrompt: 'p[name="promptText"]',
        city: 'input[name="city"]',
        errorMessage: 'p[class="errorMessage"]'
    },
    loanProperty: {
        primaryHome: 'button[value="Primary Home"]',
        rentalProperty: 'button[value="Rental Property"]',
        secondaryHome: 'button[value="Secondary Home"]',
    },
    found: {
        foundPrompt: 'p[name="promptText"]',
        noButton: 'button[name="noButton"]',
        yesButton: 'button[name="yesButton"]',
    },
    agent: {},
    priceDown: {
        price: 'input[name="price"]',
        down: 'input[name="down"]',
        errorMessage1: 'p[class="errorMessage"]',
    },
    creditScore: {
        excellent: 'button[value="Excellent"]',
        good: 'button[value="Good"]',
        fair: 'button[value="Fair"]',
        poor: 'button[value="Poor"]',
    },
    bankruptcyForeclosure: {
        neither: 'button[value="Has not been in bankruptcy or foreclosure"]',
        bankruptcy: 'button[value="Has had bankruptcy"]',
        foreclosure: 'button[value="Has had a foreclosure"]',
        both: 'button[value="Has had both a foreclosure and a bankruptcy"]',
    },
    mailingAddress: {
        addressOne: 'input[id="addressOne"]',
        addressTwo: 'input[id="addressTwo"]',
        addressThree: 'input[id="addressThree"]',
        addThreeErrorMessage: 'li[name="addThreeErrorMessage"]',
    },
    nameEmail: {
        first: 'input[id="first"]',
        last: 'input[id="last"]',
        email: 'input[id="email"]',
        addOneErrorMessage: 'li[name="addOneErrorMessage"]',
        addTwoErrroMessage: 'li[name="addTwoErrorMessage"]',
        addThreeErrorMessage: 'li[name="addThreeErrorMessage"]',
    },
    assembledQuery: {
        nameLabel: 'div[name="nameLabel"]',
        name: 'p[class="name p2"]',
        emailLabel: 'div[name="emailLabel"]',
        email: 'p[class="email p2"]',
        loanTypeLabel: 'div[name="loanTypeLabel"]',
        loanType: 'p[class="loanType p2"]',
        propertyTypeLabel: 'div[name="propertyTypeLabel"]',
        propertyType: 'p[class="propertyType p2"]',
        cityLabel: 'div[name="cityLabel"]',
        city: 'p[class="city p2"]',
        propertyPurposeLabel: 'div[name="propertyPurchaseLabel"]',
        propertyPurpose: 'p[class="propertyPurpose p2"]',
        foundLabel: 'div[name="foundLabel"]',
        found: 'p[class="found p2"]',
        agentLabel: 'div[name="agentLabel"]',
        agent: 'p[class="agent p2"]',
        priceLabel: 'div[name="priceLabel"]',
        price: 'p[class="price p2"]',
        downPaymentLabel: 'div[name="downPaymentLabel"]',
        downPayment: 'p[class="downPayment p2"]',
        creditScoreLabel: 'div[name="creditScoreLabel"]',
        creditScore: 'p[class="creditScore p2"]',
        creditHistory: 'p[class="creditHistory p2"]',
        addressLabel: 'div[name="addressLabel"]',
        sendButton: 'button[name="sendButton"]',
        restartButton: 'button[name="restartButton"]',
        addressLine1: 'span[id="addressOne"]',
        addressLine2: 'span[id="addressTwo"]',
        addressLine3: 'span[id="addressThree"]',

    },
    thankyouPage: {
        marginBtn: 'button[class="margin-btn"]',
    },
}